spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labs567_db
    username: labs567_user
    password: thestrongestpasswordiveeverseen0252_
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
crypto:
  common-passwords-file-name: data/top-100-most-common-passwords.txt